-- MySQL Script generated by MySQL Workbench
-- 04/27/16 10:18:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dal_shard_0
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dal_shard_0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dal_shard_0` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dal_shard_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dal_shard_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dal_shard_1` ;
USE `dal_shard_0` ;

-- -----------------------------------------------------
-- Table `dal_shard_0`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_0`.`person` ;

CREATE TABLE IF NOT EXISTS `dal_shard_0`.`person` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dal_shard_0`.`person_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_0`.`person_1` ;

CREATE TABLE IF NOT EXISTS `dal_shard_0`.`person_1` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dal_shard_0`.`person_2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_0`.`person_2` ;

CREATE TABLE IF NOT EXISTS `dal_shard_0`.`person_2` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dal_shard_0`.`person_3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_0`.`person_3` ;

CREATE TABLE IF NOT EXISTS `dal_shard_0`.`person_3` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dal_shard_0`.`person_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_0`.`person_0` ;

CREATE TABLE IF NOT EXISTS `dal_shard_0`.`person_0` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;

USE `dal_shard_1` ;

-- -----------------------------------------------------
-- Table `dal_shard_1`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_1`.`person` ;

CREATE TABLE IF NOT EXISTS `dal_shard_1`.`person` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dal_shard_1`.`person_0`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_1`.`person_0` ;

CREATE TABLE IF NOT EXISTS `dal_shard_1`.`person_0` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dal_shard_1`.`person_1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_1`.`person_1` ;

CREATE TABLE IF NOT EXISTS `dal_shard_1`.`person_1` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dal_shard_1`.`person_2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_1`.`person_2` ;

CREATE TABLE IF NOT EXISTS `dal_shard_1`.`person_2` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dal_shard_1`.`person_3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dal_shard_1`.`person_3` ;

CREATE TABLE IF NOT EXISTS `dal_shard_1`.`person_3` (
  `PeopleID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CityID` INT NULL,
  `ProvinceID` INT NULL,
  `CountryID` INT NULL,
  `DataChange_LastTime` DATETIME NULL,
  PRIMARY KEY (`PeopleID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
